config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  root 'pages#index'
  get '/sponsors', to: "pages#sponsors", as: :sponsors
  get '/venue', to: "pages#venue", as: :venue
  get '/giveaways', to: "pages#giveaways", as: :giveaways

end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def p1
    render :template => "pages/p1"
  end

  def sponsors
    render :template => "pages/sponsors"
  end

   def venue
    render :template => "pages/venue"
  end

  def giveaways
    render :template => "pages/giveaways"
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Ayala Group ICT Summit 2016</title>
  <meta name="google-site-verification" content="sMYlh-en8BldrbkXm1CDl8KgM24ktElNm8a7uDC1OXE" />
  <meta name="description" content="Evolving ICT: Enabling, Transforming, Redefining the Future - The Ayala Group ICT Summit is an annual event that brings together in one venue participants from across the various Ayala Group companies with an interest in Information and Communications Technology.">
<meta name="keywords" content="Ayala,ICT,Summit,2016,Information,Communications,Technology,ICT Summit,2016,Ayala Group,AC,IT,August">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/favicon4.ico" />
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
</head>
<body>

<%= yield %>

<div id="footer-top">
<center>
<a id="register" href="http://ayalaict.pouchnation.com/">REGISTER</a>
</center>
</div>
<div id="particles-js">
  <div class="row">
    <div class="col-md-4">
      <span id="cright">Ayala Group ICT Summit © 2016</span>
    </div>
    <div class="col-md-4">
      <center>
      <%=image_tag ('/assets/email.png'),:style=>"height:44px; margin-top:-12px;"%>
      </center>
    </div>
    <div class="col-md-4">
      <span id="developedby">Developed by &nbsp<a id="dblink1"href="https://github.com/enzobautista">Enzo Bautista</a></span> 
    </div>
  </div>
  <center>
  <br>
  </center>
</div>
<!-- scripts -->
<script src="assets/particles.js"></script>
<script src="assets/app.js"></script>
  <script src="/assets/wow.min.js"></script>
  <script>
  new WOW().init();
  </script> 
	<script type="text/javascript">
		function checkScroll(){
		    var startY = $('.navbar').height() * 1.2; //adjusts where transition starts

		    if($(window).scrollTop() > startY){
		        $('.navbar').addClass("scrolled");
		    }else{
		        $('.navbar').removeClass("scrolled");
		    }
		}

		if($('.navbar').length > 0){
		    $(window).on("scroll load resize", function(){
		        checkScroll();
		    });
		}
		
	</script>
  <script type='text/javascript'>
    var hashTagActive = "";
    $(".scroll").on("click touchstart" , function (event) {
        if(hashTagActive != this.hash) { //this will prevent if the user click several times the same link to freeze the scroll.
            event.preventDefault();
            //calculate destination place
            var dest = 0;
            if ($(this.hash).offset().top > $(document).height() - $(window).height()) {
                dest = $(document).height() - $(window).height();
            } else {
                dest = $(this.hash).offset().top;
            }
            //go to destination
            $('html,body').animate({
                scrollTop: dest
            }, 2000, 'swing');
            hashTagActive = this.hash;
        }
    });
</script>

</body>
</html>

app/views/pages/giveaways.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:transparent; padding:none; border-color:transparent; border:none;">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="navlink">
        <a class=""href="/#abtthe">ABOUT THE SUMMIT</a></li>
        <li class="navlink"><a class=""href="/#cioforum">CIO FORUM MEMBERS</a></li>
        <li class="navlink"><a class=""href="/#programsec">PROGRAM</a></li>

        <li class="dropdown navlink">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SPONSORS <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a  class="scroll"href="#spons-platinum">PLATINUM</a></li>
            <li><a  class="scroll"href="#spons-gold">GOLD</a></li>
            <li><a  class="scroll"href="#spons-silver">SILVER</a></li>
            <li><a  class="scroll"href="#spons-session">SESSION</a></li>
            <li><a  class="scroll"href="#spons-exhibit">EXHIBITORS</a></li>
          </ul>
        </li>
        <li class="navlink"><a href="/venue">VENUE</a></li>
         <li class="navlink"><a href="/giveaways">GIVEAWAYS</a></li>
        <li class="navlink"><a href="/venue">REGISTER</a></li>
      </ul>

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<section id="giveaways-head">
</section>
<section id="giveaways-categories">
<div id="" class="container-fluid cf4">
<div class="row" style="margin-top:-2.5vh;">
  <center>
    <div class="col-md-3 aboutcard " data-wow-duration="2s" data-wow-delay="0s">
      <div class="aboutcardin">
        <div class="abimg" style="background-image:url('/assets/bred.png');">
          <div class="imgoverlay">
            <span class="aboutcardtitle" style="color:white!important;">
            <br>EARLY BIRD</span>
            
          </div>
        </div>
        
        <div class="textpadd">
        <span class="aboutcardtext">
          The early bird...
        </span>
        <center>
        </center>
        </div>
      </div>
    </div>
    <div class="col-md-3 aboutcard " data-wow-duration="2s" data-wow-delay="0s">
      <div class="aboutcardin">
        <div class="abimg" style="background-image:url('/assets/participation.png');">
          <div class="imgoverlay">
            <span class="aboutcardtitle" style="color:white!important;">
            <br>SESSION PARTICIPATION</span>
            
          </div>
        </div>
        
        <div class="textpadd">
        <span class="aboutcardtext">
          The early bird...
        </span>
        <center>
        </center>
        </div>
      </div>
    </div>
    <div class="col-md-3 aboutcard " data-wow-duration="2s" data-wow-delay="0s">
      <div class="aboutcardin">
        <div class="abimg" style="background-image:url('/assets/clover.png');">
          <div class="imgoverlay">
            <span class="aboutcardtitle" style="color:white!important;">
            <br>RAFFLE</span>
            
          </div>
        </div>
        
        <div class="textpadd">
        <span class="aboutcardtext">
          The early bird...
        </span>
        <center>
        </center>
        </div>
      </div>
    </div>
    <div class="col-md-3 aboutcard " data-wow-duration="2s" data-wow-delay="0s">
      <div class="aboutcardin">
        <div class="abimg" style="background-image:url('/assets/bred.png');">
          <div class="imgoverlay">
            <span class="aboutcardtitle" style="color:white!important;">
            <br>LOOT</span>
            
          </div>
        </div>
        
        <div class="textpadd">
        <span class="aboutcardtext">
          The early bird...
        </span>
        <center>
        </center>
        </div>
      </div>
    </div>

    </center>
</div>
</div>
</section>

app/views/pages/sponsors.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:transparent; padding:none; border-color:transparent; border:none;">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="navlink">
        <a class=""href="/#abtthe">ABOUT THE SUMMIT</a></li>
        <li class="navlink"><a class=""href="/#cioforum">CIO FORUM MEMBERS</a></li>
        <li class="navlink"><a class=""href="/#programsec">PROGRAM</a></li>

        <li class="dropdown navlink">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SPONSORS <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a  class="scroll"href="#spons-platinum">PLATINUM</a></li>
            <li><a  class="scroll"href="#spons-gold">GOLD</a></li>
            <li><a  class="scroll"href="#spons-silver">SILVER</a></li>
            <li><a  class="scroll"href="#spons-session">SESSION</a></li>
            <li><a  class="scroll"href="#spons-exhibit">EXHIBITORS</a></li>
          </ul>
        </li>
        <li class="navlink"><a href="/venue">VENUE</a></li>
         <li class="navlink"><a href="/giveaways">GIVEAWAYS</a></li>
        <li class="navlink"><a href="/venue">REGISTER</a></li>
      </ul>

      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<section id="spons-head">
</section>
<section id="spons-platinum">
<br>
	<center>
		<div class="sponsheader">PLATINUM SPONSORS</div><br>
		<div class="row">
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-accenture.jpg'),:style=>"width:210px; margin-top:5px;"%>
			</div>
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-AISI.png'),:style=>"width:400px;"%>
			</div>
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-barhead.png'),:style=>"width:240px; margin-top:30px;"%>

			</div>

		</div>
		<br>
		<div class="row">
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-brother.jpg'),:style=>"width:210px; margin-top:5px;"%>
			</div>
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-globe.png'),:style=>"width:270px;"%>
			</div>
			<div class="col-md-4" style="padding-bottom:1px;">
			<%=image_tag ('/assets/sponsors/plat-huawei.png'),:style=>"width:105px; margin-top:-10px;"%>

			</div>
		</div>
		<div class="row" style="">
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-oracle.jpg'),:style=>"width:220px; margin-top:30px;"%>
			</div>
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/plat-ramco.png'),:style=>"width:190px; margin-top:5px;"%>
			</div>
		</div>
		
	</center>
</section>
<section id="spons-gold">
	<center>
		<div class="sponsheader">GOLD SPONSOR</div>
		<div class="row" style="width:70vw;">
			<div class="col-md-4"></div>
			<div class="col-md-4">
			<%=image_tag ('/assets/sponsors/gold-sapphire.png'),:style=>"width:180px; margin-top:20px;"%>
			</div>
		</div>
	</center>
</section>
<section id="spons-silver">
	<center>
		<div class="sponsheader">SILVER SPONSORS</div><br><br>
		<div class="row">
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-anaplan.jpg'),:style=>"width:140px; margin-top:5px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-fis.jpg'),:style=>"width:110px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-fortinet.jpg'),:style=>"width:200px; margin-top:20px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-fujitsu.jpg'),:style=>"width:180px; margin-top:-20px;"%>

			</div>

		</div>
		<br>
		<div class="row">
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-intel.jpg'),:style=>"width:170px; margin-top:5px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-nmi.png'),:style=>"width:130px; margin-top:-30px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-sas.png'),:style=>"width:130px; margin-top:0px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-softwareone.png'),:style=>"width:190px; margin-top:20px;"%>

			</div>

		</div>
		<div class="row">
			<div class="col-md-3">
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-tm.jpg'),:style=>"width:150px; margin-top:25px;"%>
			</div>
			<div class="col-md-3">
			<%=image_tag ('/assets/sponsors/silver-trends.jpg'),:style=>"width:260px; margin-top:20px;"%>
			</div>
			<div class="col-md-3">
			</div>

		</div>
	</center>
</section>
<section id="spons-session">
	<center>
		<div class="sponsheader">SESSION SPONSORS</div><br><br><br>
		<div class="row">
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-fpti.png'),:style=>"width:135px; margin-top:-15px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-infomax.png'),:style=>"width:160px; margin-top:0px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-pwc.png'),:style=>"width:110px;margin-top:-40px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-sap.PNG'),:style=>"width:120px; margin-top:-20px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-service.png'),:style=>"width:200px; margin-top:-10px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/session-teradata.png'),:style=>"width:150px; margin-top:-10px;"%>
			</div>
	</div>
	</center>
</section>
<section id="spons-exhibit">
	<center>
		<div class="sponsheader">EXHIBIT SPONSORS</div><br><br><br>
		<div class="row">
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-cloud.jpg'),:style=>"width:135px; margin-top:-15px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-equicom.png'),:style=>"width:160px; margin-top:-3px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-evi.png'),:style=>"width:160px;margin-top:-5px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-fast.jpg'),:style=>"width:120px; margin-top:-15px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-inaveit.png'),:style=>"width:130px; margin-top:-32px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-mctri.png'),:style=>"width:160px; margin-top:-10px;"%>
			</div>
		</div>
				<div class="row">
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-net4site.jpg'),:style=>"width:140px; margin-top:15px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-questronix.jpg'),:style=>"width:85px; margin-top:-7px;"%>
			</div>
			<div class="col-md-2">
			<%=image_tag ('/assets/sponsors/ex-smsgt.jpg'),:style=>"width:130px;margin-top:15px;"%>
			</div>
	</div>
	</center>
</section>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>